[package]
name = "fbot-vss-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.0"
socket2 = { version = "0.3.4", features = ["reuseport"] }
protobuf = "2"


[build-dependencies]
protoc-rust = "2.0"