[package]
name = "fbot-vss-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vss-core = { git = "https://github.com/LucasMartinsUthi/VSS-CoreRust", branch = "master" }
